//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebForm.Service {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NHANVIEN", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
    [System.SerializableAttribute()]
    public partial class NHANVIEN : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DIACHIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HONVField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> HSLUONGField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MANQLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MANVField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> MAPHONGField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> NGAYSINHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PHAIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TENLOTNVField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TENNVField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DIACHI {
            get {
                return this.DIACHIField;
            }
            set {
                if ((object.ReferenceEquals(this.DIACHIField, value) != true)) {
                    this.DIACHIField = value;
                    this.RaisePropertyChanged("DIACHI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HONV {
            get {
                return this.HONVField;
            }
            set {
                if ((object.ReferenceEquals(this.HONVField, value) != true)) {
                    this.HONVField = value;
                    this.RaisePropertyChanged("HONV");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> HSLUONG {
            get {
                return this.HSLUONGField;
            }
            set {
                if ((this.HSLUONGField.Equals(value) != true)) {
                    this.HSLUONGField = value;
                    this.RaisePropertyChanged("HSLUONG");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MANQL {
            get {
                return this.MANQLField;
            }
            set {
                if ((object.ReferenceEquals(this.MANQLField, value) != true)) {
                    this.MANQLField = value;
                    this.RaisePropertyChanged("MANQL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MANV {
            get {
                return this.MANVField;
            }
            set {
                if ((object.ReferenceEquals(this.MANVField, value) != true)) {
                    this.MANVField = value;
                    this.RaisePropertyChanged("MANV");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MAPHONG {
            get {
                return this.MAPHONGField;
            }
            set {
                if ((this.MAPHONGField.Equals(value) != true)) {
                    this.MAPHONGField = value;
                    this.RaisePropertyChanged("MAPHONG");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> NGAYSINH {
            get {
                return this.NGAYSINHField;
            }
            set {
                if ((this.NGAYSINHField.Equals(value) != true)) {
                    this.NGAYSINHField = value;
                    this.RaisePropertyChanged("NGAYSINH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PHAI {
            get {
                return this.PHAIField;
            }
            set {
                if ((object.ReferenceEquals(this.PHAIField, value) != true)) {
                    this.PHAIField = value;
                    this.RaisePropertyChanged("PHAI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TENLOTNV {
            get {
                return this.TENLOTNVField;
            }
            set {
                if ((object.ReferenceEquals(this.TENLOTNVField, value) != true)) {
                    this.TENLOTNVField = value;
                    this.RaisePropertyChanged("TENLOTNV");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TENNV {
            get {
                return this.TENNVField;
            }
            set {
                if ((object.ReferenceEquals(this.TENNVField, value) != true)) {
                    this.TENNVField = value;
                    this.RaisePropertyChanged("TENNV");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PHONGBAN", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
    [System.SerializableAttribute()]
    public partial class PHONGBAN : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MAPHONGField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> NGAYNHANCHUCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TENPHONGField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TRUONGPHONGField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MAPHONG {
            get {
                return this.MAPHONGField;
            }
            set {
                if ((this.MAPHONGField.Equals(value) != true)) {
                    this.MAPHONGField = value;
                    this.RaisePropertyChanged("MAPHONG");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> NGAYNHANCHUC {
            get {
                return this.NGAYNHANCHUCField;
            }
            set {
                if ((this.NGAYNHANCHUCField.Equals(value) != true)) {
                    this.NGAYNHANCHUCField = value;
                    this.RaisePropertyChanged("NGAYNHANCHUC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TENPHONG {
            get {
                return this.TENPHONGField;
            }
            set {
                if ((object.ReferenceEquals(this.TENPHONGField, value) != true)) {
                    this.TENPHONGField = value;
                    this.RaisePropertyChanged("TENPHONG");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TRUONGPHONG {
            get {
                return this.TRUONGPHONGField;
            }
            set {
                if ((object.ReferenceEquals(this.TRUONGPHONGField, value) != true)) {
                    this.TRUONGPHONGField = value;
                    this.RaisePropertyChanged("TRUONGPHONG");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Service.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EvenNumber", ReplyAction="http://tempuri.org/IService1/EvenNumberResponse")]
        string EvenNumber(int[] arr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EvenNumber", ReplyAction="http://tempuri.org/IService1/EvenNumberResponse")]
        System.Threading.Tasks.Task<string> EvenNumberAsync(int[] arr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetEmployee", ReplyAction="http://tempuri.org/IService1/GetEmployeeResponse")]
        WebForm.Service.NHANVIEN[] GetEmployee();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetEmployee", ReplyAction="http://tempuri.org/IService1/GetEmployeeResponse")]
        System.Threading.Tasks.Task<WebForm.Service.NHANVIEN[]> GetEmployeeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SearchEmployee", ReplyAction="http://tempuri.org/IService1/SearchEmployeeResponse")]
        WebForm.Service.NHANVIEN SearchEmployee(string maNV);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SearchEmployee", ReplyAction="http://tempuri.org/IService1/SearchEmployeeResponse")]
        System.Threading.Tasks.Task<WebForm.Service.NHANVIEN> SearchEmployeeAsync(string maNV);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddEmployee", ReplyAction="http://tempuri.org/IService1/AddEmployeeResponse")]
        bool AddEmployee(string maNV, string hoNV, string tenLopNV, string tenNV, System.DateTime ngaySinh, string phai, string diaChi, decimal hsLuong, string maNQL, int maPhong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddEmployee", ReplyAction="http://tempuri.org/IService1/AddEmployeeResponse")]
        System.Threading.Tasks.Task<bool> AddEmployeeAsync(string maNV, string hoNV, string tenLopNV, string tenNV, System.DateTime ngaySinh, string phai, string diaChi, decimal hsLuong, string maNQL, int maPhong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateEmployee", ReplyAction="http://tempuri.org/IService1/UpdateEmployeeResponse")]
        bool UpdateEmployee(string maNV, string hoNV, string tenLopNV, string tenNV, System.DateTime ngaySinh, string phai, string diaChi, decimal hsLuong, string maNQL, int maPhong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateEmployee", ReplyAction="http://tempuri.org/IService1/UpdateEmployeeResponse")]
        System.Threading.Tasks.Task<bool> UpdateEmployeeAsync(string maNV, string hoNV, string tenLopNV, string tenNV, System.DateTime ngaySinh, string phai, string diaChi, decimal hsLuong, string maNQL, int maPhong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteEmployee", ReplyAction="http://tempuri.org/IService1/DeleteEmployeeResponse")]
        bool DeleteEmployee(string maNV);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteEmployee", ReplyAction="http://tempuri.org/IService1/DeleteEmployeeResponse")]
        System.Threading.Tasks.Task<bool> DeleteEmployeeAsync(string maNV);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetRoom", ReplyAction="http://tempuri.org/IService1/GetRoomResponse")]
        WebForm.Service.PHONGBAN[] GetRoom();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetRoom", ReplyAction="http://tempuri.org/IService1/GetRoomResponse")]
        System.Threading.Tasks.Task<WebForm.Service.PHONGBAN[]> GetRoomAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WebForm.Service.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WebForm.Service.IService1>, WebForm.Service.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string EvenNumber(int[] arr) {
            return base.Channel.EvenNumber(arr);
        }
        
        public System.Threading.Tasks.Task<string> EvenNumberAsync(int[] arr) {
            return base.Channel.EvenNumberAsync(arr);
        }
        
        public WebForm.Service.NHANVIEN[] GetEmployee() {
            return base.Channel.GetEmployee();
        }
        
        public System.Threading.Tasks.Task<WebForm.Service.NHANVIEN[]> GetEmployeeAsync() {
            return base.Channel.GetEmployeeAsync();
        }
        
        public WebForm.Service.NHANVIEN SearchEmployee(string maNV) {
            return base.Channel.SearchEmployee(maNV);
        }
        
        public System.Threading.Tasks.Task<WebForm.Service.NHANVIEN> SearchEmployeeAsync(string maNV) {
            return base.Channel.SearchEmployeeAsync(maNV);
        }
        
        public bool AddEmployee(string maNV, string hoNV, string tenLopNV, string tenNV, System.DateTime ngaySinh, string phai, string diaChi, decimal hsLuong, string maNQL, int maPhong) {
            return base.Channel.AddEmployee(maNV, hoNV, tenLopNV, tenNV, ngaySinh, phai, diaChi, hsLuong, maNQL, maPhong);
        }
        
        public System.Threading.Tasks.Task<bool> AddEmployeeAsync(string maNV, string hoNV, string tenLopNV, string tenNV, System.DateTime ngaySinh, string phai, string diaChi, decimal hsLuong, string maNQL, int maPhong) {
            return base.Channel.AddEmployeeAsync(maNV, hoNV, tenLopNV, tenNV, ngaySinh, phai, diaChi, hsLuong, maNQL, maPhong);
        }
        
        public bool UpdateEmployee(string maNV, string hoNV, string tenLopNV, string tenNV, System.DateTime ngaySinh, string phai, string diaChi, decimal hsLuong, string maNQL, int maPhong) {
            return base.Channel.UpdateEmployee(maNV, hoNV, tenLopNV, tenNV, ngaySinh, phai, diaChi, hsLuong, maNQL, maPhong);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateEmployeeAsync(string maNV, string hoNV, string tenLopNV, string tenNV, System.DateTime ngaySinh, string phai, string diaChi, decimal hsLuong, string maNQL, int maPhong) {
            return base.Channel.UpdateEmployeeAsync(maNV, hoNV, tenLopNV, tenNV, ngaySinh, phai, diaChi, hsLuong, maNQL, maPhong);
        }
        
        public bool DeleteEmployee(string maNV) {
            return base.Channel.DeleteEmployee(maNV);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteEmployeeAsync(string maNV) {
            return base.Channel.DeleteEmployeeAsync(maNV);
        }
        
        public WebForm.Service.PHONGBAN[] GetRoom() {
            return base.Channel.GetRoom();
        }
        
        public System.Threading.Tasks.Task<WebForm.Service.PHONGBAN[]> GetRoomAsync() {
            return base.Channel.GetRoomAsync();
        }
    }
}
