//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinForm.Service {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Service.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Count_Div2_NotDiv4", ReplyAction="http://tempuri.org/IService/Count_Div2_NotDiv4Response")]
        string Count_Div2_NotDiv4(int[] arr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Count_Div2_NotDiv4", ReplyAction="http://tempuri.org/IService/Count_Div2_NotDiv4Response")]
        System.Threading.Tasks.Task<string> Count_Div2_NotDiv4Async(int[] arr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SortOddNumberDescending", ReplyAction="http://tempuri.org/IService/SortOddNumberDescendingResponse")]
        int[] SortOddNumberDescending(int[] arr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SortOddNumberDescending", ReplyAction="http://tempuri.org/IService/SortOddNumberDescendingResponse")]
        System.Threading.Tasks.Task<int[]> SortOddNumberDescendingAsync(int[] arr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SumOddNumber", ReplyAction="http://tempuri.org/IService/SumOddNumberResponse")]
        int SumOddNumber(int[] arr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SumOddNumber", ReplyAction="http://tempuri.org/IService/SumOddNumberResponse")]
        System.Threading.Tasks.Task<int> SumOddNumberAsync(int[] arr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/PrintArray", ReplyAction="http://tempuri.org/IService/PrintArrayResponse")]
        string PrintArray(int[] arr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/PrintArray", ReplyAction="http://tempuri.org/IService/PrintArrayResponse")]
        System.Threading.Tasks.Task<string> PrintArrayAsync(int[] arr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Count_Div4_Div5", ReplyAction="http://tempuri.org/IService/Count_Div4_Div5Response")]
        string Count_Div4_Div5(int[] arr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Count_Div4_Div5", ReplyAction="http://tempuri.org/IService/Count_Div4_Div5Response")]
        System.Threading.Tasks.Task<string> Count_Div4_Div5Async(int[] arr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SortEvenNumberAscending", ReplyAction="http://tempuri.org/IService/SortEvenNumberAscendingResponse")]
        int[] SortEvenNumberAscending(int[] arr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SortEvenNumberAscending", ReplyAction="http://tempuri.org/IService/SortEvenNumberAscendingResponse")]
        System.Threading.Tasks.Task<int[]> SortEvenNumberAscendingAsync(int[] arr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Average", ReplyAction="http://tempuri.org/IService/AverageResponse")]
        double Average(int[] arr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Average", ReplyAction="http://tempuri.org/IService/AverageResponse")]
        System.Threading.Tasks.Task<double> AverageAsync(int[] arr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Count_PrintOddNumber", ReplyAction="http://tempuri.org/IService/Count_PrintOddNumberResponse")]
        string Count_PrintOddNumber(int[] arr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Count_PrintOddNumber", ReplyAction="http://tempuri.org/IService/Count_PrintOddNumberResponse")]
        System.Threading.Tasks.Task<string> Count_PrintOddNumberAsync(int[] arr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Count_PrintEvenNumber", ReplyAction="http://tempuri.org/IService/Count_PrintEvenNumberResponse")]
        string Count_PrintEvenNumber(int[] arr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Count_PrintEvenNumber", ReplyAction="http://tempuri.org/IService/Count_PrintEvenNumberResponse")]
        System.Threading.Tasks.Task<string> Count_PrintEvenNumberAsync(int[] arr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Sort_OddNumberDescending_EvenNumberAscending", ReplyAction="http://tempuri.org/IService/Sort_OddNumberDescending_EvenNumberAscendingResponse")]
        int[] Sort_OddNumberDescending_EvenNumberAscending(int[] arr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Sort_OddNumberDescending_EvenNumberAscending", ReplyAction="http://tempuri.org/IService/Sort_OddNumberDescending_EvenNumberAscendingResponse")]
        System.Threading.Tasks.Task<int[]> Sort_OddNumberDescending_EvenNumberAscendingAsync(int[] arr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SumArray", ReplyAction="http://tempuri.org/IService/SumArrayResponse")]
        int SumArray(int[] arr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SumArray", ReplyAction="http://tempuri.org/IService/SumArrayResponse")]
        System.Threading.Tasks.Task<int> SumArrayAsync(int[] arr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/IsPrime", ReplyAction="http://tempuri.org/IService/IsPrimeResponse")]
        bool IsPrime(int n);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/IsPrime", ReplyAction="http://tempuri.org/IService/IsPrimeResponse")]
        System.Threading.Tasks.Task<bool> IsPrimeAsync(int n);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Count_Sum_Prime", ReplyAction="http://tempuri.org/IService/Count_Sum_PrimeResponse")]
        string Count_Sum_Prime(int[] arr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Count_Sum_Prime", ReplyAction="http://tempuri.org/IService/Count_Sum_PrimeResponse")]
        System.Threading.Tasks.Task<string> Count_Sum_PrimeAsync(int[] arr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Sort_EvenNumberAscending_OddNumberDescending", ReplyAction="http://tempuri.org/IService/Sort_EvenNumberAscending_OddNumberDescendingResponse")]
        int[] Sort_EvenNumberAscending_OddNumberDescending(int[] arr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Sort_EvenNumberAscending_OddNumberDescending", ReplyAction="http://tempuri.org/IService/Sort_EvenNumberAscending_OddNumberDescendingResponse")]
        System.Threading.Tasks.Task<int[]> Sort_EvenNumberAscending_OddNumberDescendingAsync(int[] arr);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : WinForm.Service.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<WinForm.Service.IService>, WinForm.Service.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Count_Div2_NotDiv4(int[] arr) {
            return base.Channel.Count_Div2_NotDiv4(arr);
        }
        
        public System.Threading.Tasks.Task<string> Count_Div2_NotDiv4Async(int[] arr) {
            return base.Channel.Count_Div2_NotDiv4Async(arr);
        }
        
        public int[] SortOddNumberDescending(int[] arr) {
            return base.Channel.SortOddNumberDescending(arr);
        }
        
        public System.Threading.Tasks.Task<int[]> SortOddNumberDescendingAsync(int[] arr) {
            return base.Channel.SortOddNumberDescendingAsync(arr);
        }
        
        public int SumOddNumber(int[] arr) {
            return base.Channel.SumOddNumber(arr);
        }
        
        public System.Threading.Tasks.Task<int> SumOddNumberAsync(int[] arr) {
            return base.Channel.SumOddNumberAsync(arr);
        }
        
        public string PrintArray(int[] arr) {
            return base.Channel.PrintArray(arr);
        }
        
        public System.Threading.Tasks.Task<string> PrintArrayAsync(int[] arr) {
            return base.Channel.PrintArrayAsync(arr);
        }
        
        public string Count_Div4_Div5(int[] arr) {
            return base.Channel.Count_Div4_Div5(arr);
        }
        
        public System.Threading.Tasks.Task<string> Count_Div4_Div5Async(int[] arr) {
            return base.Channel.Count_Div4_Div5Async(arr);
        }
        
        public int[] SortEvenNumberAscending(int[] arr) {
            return base.Channel.SortEvenNumberAscending(arr);
        }
        
        public System.Threading.Tasks.Task<int[]> SortEvenNumberAscendingAsync(int[] arr) {
            return base.Channel.SortEvenNumberAscendingAsync(arr);
        }
        
        public double Average(int[] arr) {
            return base.Channel.Average(arr);
        }
        
        public System.Threading.Tasks.Task<double> AverageAsync(int[] arr) {
            return base.Channel.AverageAsync(arr);
        }
        
        public string Count_PrintOddNumber(int[] arr) {
            return base.Channel.Count_PrintOddNumber(arr);
        }
        
        public System.Threading.Tasks.Task<string> Count_PrintOddNumberAsync(int[] arr) {
            return base.Channel.Count_PrintOddNumberAsync(arr);
        }
        
        public string Count_PrintEvenNumber(int[] arr) {
            return base.Channel.Count_PrintEvenNumber(arr);
        }
        
        public System.Threading.Tasks.Task<string> Count_PrintEvenNumberAsync(int[] arr) {
            return base.Channel.Count_PrintEvenNumberAsync(arr);
        }
        
        public int[] Sort_OddNumberDescending_EvenNumberAscending(int[] arr) {
            return base.Channel.Sort_OddNumberDescending_EvenNumberAscending(arr);
        }
        
        public System.Threading.Tasks.Task<int[]> Sort_OddNumberDescending_EvenNumberAscendingAsync(int[] arr) {
            return base.Channel.Sort_OddNumberDescending_EvenNumberAscendingAsync(arr);
        }
        
        public int SumArray(int[] arr) {
            return base.Channel.SumArray(arr);
        }
        
        public System.Threading.Tasks.Task<int> SumArrayAsync(int[] arr) {
            return base.Channel.SumArrayAsync(arr);
        }
        
        public bool IsPrime(int n) {
            return base.Channel.IsPrime(n);
        }
        
        public System.Threading.Tasks.Task<bool> IsPrimeAsync(int n) {
            return base.Channel.IsPrimeAsync(n);
        }
        
        public string Count_Sum_Prime(int[] arr) {
            return base.Channel.Count_Sum_Prime(arr);
        }
        
        public System.Threading.Tasks.Task<string> Count_Sum_PrimeAsync(int[] arr) {
            return base.Channel.Count_Sum_PrimeAsync(arr);
        }
        
        public int[] Sort_EvenNumberAscending_OddNumberDescending(int[] arr) {
            return base.Channel.Sort_EvenNumberAscending_OddNumberDescending(arr);
        }
        
        public System.Threading.Tasks.Task<int[]> Sort_EvenNumberAscending_OddNumberDescendingAsync(int[] arr) {
            return base.Channel.Sort_EvenNumberAscending_OddNumberDescendingAsync(arr);
        }
    }
}
